

### Obtener todos los usuarios
GET http://localhost:3000/api/obtenerUsuario

### Crear todos los usuarios
POST http://localhost:3000/api//crearUsuario

### Modificar  usuario por id
PUT http://localhost:3000/api/modificarUsuario/:_id

### Eliminar usuario por id
DELETE http://localhost:3000/api/eliminarUsuario/:_id